# SPDX-License-Identifier: FSFAP OR GPL-2.0-or-later
repository: ma8ma/JDim
theme: jekyll-theme-cayman
markdown: GFM
plugins:
  - jekyll-redirect-from
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter
exclude:
  - Gemfile*
  - Makefile
  - README.md
  - backup_bund/ruby
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
lang: ja
baseurl: /JDim
defaults:
  - scope:
      path: "manual"
    values:
      permalink: /:basename/
