name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  compiler-22:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-11
      CXX: g++-11
    steps:
      - uses: actions/checkout@v3
      - name: dependencies installation
        run: |
          sudo apt update
          sudo apt install libgnutls28-dev libgtest-dev libgtkmm-3.0-dev meson zlib1g-dev g++-11
      - name: meson setup builddir -Dbuildtype=debug -Dcpp_args="-D_DEBUG" -Dwerror=true
        run: meson setup builddir -Dbuildtype=debug -Dcpp_args="-D_DEBUG" -Dwerror=true
      - name: ninja -C builddir -k0
        run: ninja -C builddir -k0
      - name: meson test -v -C builddir
        run: meson test -v -C builddir
      - name: ./builddir/src/jdim -V
        run: ./builddir/src/jdim -V

  Unity-build-22-sizeN:
    runs-on: ubuntu-22.04
    env:
      CC: gcc-11
      CXX: g++-11
    strategy:
      matrix:
        unity_size:
          - 2
          - 4
          - 6
          - 8
          - 10
          - 12
          - 14
          - 16
          - 18
          - 20
          - 22
          - 24
          - 26
          - 28
          - 30
          - 32
          - 34
          - 36
          - 38
          - 40
          - 42
          - 44
          - 46
          - 48
          - 50
          - 52
          - 54
          - 56
          - 58
          - 60
          - 62
          - 64
    steps:
      - uses: actions/checkout@v3
      - name: dependencies installation
        run: |
          sudo apt update
          sudo apt install libgnutls28-dev libgtest-dev libgtkmm-3.0-dev meson zlib1g-dev g++-11
      - name: meson setup builddir -Dunity=on -Dunity_size=${{ matrix.unity_size }} -Dbuildtype=debug -Dcpp_args="-D_DEBUG" -Dwerror=true
        run: meson setup builddir -Dunity=on -Dunity_size=${{ matrix.unity_size }} -Dbuildtype=debug -Dcpp_args="-D_DEBUG" -Dwerror=true
      - name: ninja -C builddir -k0
        run: ninja -C builddir -k0
      - name: meson test -v -C builddir
        run: meson test -v -C builddir
      - name: ./builddir/src/jdim -V
        run: ./builddir/src/jdim -V
