name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  ASan-22:
    runs-on: ubuntu-22.04
    env:
      CC: ${{ matrix.sets.cc }}
      CXX: ${{ matrix.sets.cxx }}
      CPP_ARGS: -D_DEBUG
      CPP_LINK_ARGS: -Wl,--push-state,--no-as-needed -lcrypt -Wl,--pop-state
    strategy:
      matrix:
        sets:
          - cc: gcc-11
            cxx: g++-11
            package: g++-11
    steps:
      - uses: actions/checkout@v3
      - name: dependencies installation
        run: |
          sudo apt update
          sudo apt install libgnutls28-dev libgtest-dev libgtkmm-3.0-dev meson zlib1g-dev ${{ matrix.sets.package }}
      - name: meson builddir -Db_sanitize=address,undefined -Dbuildtype=debug -Dcpp_args="${CPP_ARGS}" -Dcpp_link_args="${CPP_LINK_ARGS}"
        run: meson builddir -Db_sanitize=address,undefined -Dbuildtype=debug -Dcpp_args="${CPP_ARGS}" -Dcpp_link_args="${CPP_LINK_ARGS}"

      - name: ninja -C builddir
        run: ninja -C builddir
      - name: meson test -v -C builddir
        run: meson test -v -C builddir
      - name: ./builddir/src/jdim -V
        run: ./builddir/src/jdim -V
