name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  autotools:
    runs-on: ${{ matrix.sets.os }}
    env:
      CC: ${{ matrix.sets.cc }}
      CXX: ${{ matrix.sets.cxx }}
      CXXFLAGS: -Og -pipe -D_DEBUG
    strategy:
      fail-fast: false
      matrix:
        sets:
          - os: ubuntu-20.04
            cc: gcc-8
            cxx: g++-8
            package: g++-8

          - os: ubuntu-20.04
            cc: gcc-9
            cxx: g++-9
            package: g++-9

          - os: ubuntu-20.04
            cc: gcc-10
            cxx: g++-10
            package: g++-10


          - os: ubuntu-20.04
            cc: clang-7
            cxx: clang++-7
            package: clang-7

          - os: ubuntu-20.04
            cc: clang-8
            cxx: clang++-8
            package: clang-8

          - os: ubuntu-20.04
            cc: clang-9
            cxx: clang++-9
            package: clang-9

          - os: ubuntu-20.04
            cc: clang-10
            cxx: clang++-10
            package: clang-10

          - os: ubuntu-20.04
            cc: clang-11
            cxx: clang++-11
            package: clang-11

          - os: ubuntu-20.04
            cc: clang-12
            cxx: clang++-12
            package: clang-12


          - os: ubuntu-22.04
            cc: gcc-9
            cxx: g++-9
            package: g++-9

          - os: ubuntu-22.04
            cc: gcc-10
            cxx: g++-10
            package: g++-10

          - os: ubuntu-22.04
            cc: gcc-11
            cxx: g++-11
            package: g++-11

          - os: ubuntu-22.04
            cc: gcc-12
            cxx: g++-12
            package: g++-12


          - os: ubuntu-22.04
            cc: clang-11
            cxx: clang++-11
            package: clang-11

          - os: ubuntu-22.04
            cc: clang-12
            cxx: clang++-12
            package: clang-12

          - os: ubuntu-22.04
            cc: clang-13
            cxx: clang++-13
            package: clang-13

          - os: ubuntu-22.04
            cc: clang-14
            cxx: clang++-14
            package: clang-14
    steps:
    - uses: actions/checkout@v3
    - name: dependencies installation
      run: |
        sudo apt update
        sudo apt install autoconf-archive libgnutls28-dev libgtest-dev libgtkmm-3.0-dev libltdl-dev libtool zlib1g-dev ${{ matrix.sets.package }}
    - name: autoreconf -i
      run: autoreconf -i
    - name: ./configure
      run: ./configure
    - name: make -j$(nproc)
      run: make -j$(nproc)
    - name: make check -j$(nproc)
      run: make check -j$(nproc)
    - name: ./src/jdim -V
      run: ./src/jdim -V

  meson:
    runs-on: ${{ matrix.sets.os }}
    env:
      CC: ${{ matrix.sets.cc }}
      CXX: ${{ matrix.sets.cxx }}
    strategy:
      fail-fast: false
      matrix:
        sets:
          - os: ubuntu-20.04
            cc: gcc-8
            cxx: g++-8
            package: g++-8

          - os: ubuntu-20.04
            cc: gcc-9
            cxx: g++-9
            package: g++-9

          - os: ubuntu-20.04
            cc: gcc-10
            cxx: g++-10
            package: g++-10


          - os: ubuntu-20.04
            cc: clang-7
            cxx: clang++-7
            package: clang-7

          - os: ubuntu-20.04
            cc: clang-8
            cxx: clang++-8
            package: clang-8

          - os: ubuntu-20.04
            cc: clang-9
            cxx: clang++-9
            package: clang-9

          - os: ubuntu-20.04
            cc: clang-10
            cxx: clang++-10
            package: clang-10

          - os: ubuntu-20.04
            cc: clang-11
            cxx: clang++-11
            package: clang-11

          - os: ubuntu-20.04
            cc: clang-12
            cxx: clang++-12
            package: clang-12


          - os: ubuntu-22.04
            cc: gcc-9
            cxx: g++-9
            package: g++-9

          - os: ubuntu-22.04
            cc: gcc-10
            cxx: g++-10
            package: g++-10

          - os: ubuntu-22.04
            cc: gcc-11
            cxx: g++-11
            package: g++-11

          - os: ubuntu-22.04
            cc: gcc-12
            cxx: g++-12
            package: g++-12


          - os: ubuntu-22.04
            cc: clang-11
            cxx: clang++-11
            package: clang-11

          - os: ubuntu-22.04
            cc: clang-12
            cxx: clang++-12
            package: clang-12

          - os: ubuntu-22.04
            cc: clang-13
            cxx: clang++-13
            package: clang-13

          - os: ubuntu-22.04
            cc: clang-14
            cxx: clang++-14
            package: clang-14
    steps:
    - uses: actions/checkout@v3
    - name: dependencies installation
      run: |
        sudo apt update
        sudo apt install libgnutls28-dev libgtest-dev libgtkmm-3.0-dev ninja-build zlib1g-dev ${{ matrix.sets.package }}
    - name: meson builddir -Dbuildtype=debugoptimized -Dcpp_args="-D_DEBUG"
      run: meson builddir -Dbuildtype=debugoptimized -Dcpp_args="-D_DEBUG"
    - name: ninja -C builddir
      run: ninja -C builddir
    - name: meson test -C builddir
      run: meson test -C builddir
    - name: ./builddir/src/jdim -V
      run: ./builddir/src/jdim -V
